import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist, Nunito_Sans } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Nav from "./_components/navbar";
import Footer from "./_components/footer";
import Hero from "./_components/hero";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

const nunitosans = Nunito_Sans({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-nunito-sans",

})

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${nunitosans.variable}`} lang="en">
			<body className="flex flex-col min-h-screen bg-primary text-white">
				<Nav />
				
				<div className="flex-1">
					<Hero />
					<TRPCReactProvider>{children}</TRPCReactProvider>
				</div>
				<Footer />
			</body>

		</html>
	);
}
